var index = {
	css: ["../assets/global/plugins/pace/themes/pace-theme-flash.css",
		"../assets/global/plugins/font-awesome/css/font-awesome.css",
		"../assets/global/plugins/simple-line-icons/simple-line-icons.css",
		"../assets/global/plugins/bootstrap/css/bootstrap.css",
		"../assets/global/plugins/uniform/css/uniform.default.css",
		"../assets/global/plugins/bootstrap-switch/css/bootstrap-switch.css",
		"../assets/global/plugins/morris/morris.css",
		"../assets/pages/css/tasks.css",
		"../assets/global/plugins/bootstrap-daterangepicker/daterangepicker.css",
		"../assets/global/plugins/bootstrap-toastr/toastr.css",
		"../assets/global/plugins/cubeportfolio/css/cubeportfolio.css",
		"../assets/global/css/components-rounded.css",
		"../assets/global/css/plugins-md.css",
		"../assets/layouts/layout/css/layout.css",
		"../assets/layouts/layout/css/themes/darkblue.css",
		"../assets/layouts/layout/css/custom.css"
	],
	js: ["../assets/global/plugins/jquery.js",
		"../assets/global/plugins/jquery.base64.js",
		"../assets/global/plugins/bootstrap/js/bootstrap.js",
		"../assets/global/plugins/bootstrap-hover-dropdown/bootstrap-hover-dropdown.js",
		"../assets/global/plugins/jquery-slimscroll/jquery.slimscroll.js",
		"../assets/global/plugins/jquery.blockui.js",
		"../assets/global/plugins/js.cookie.js",
		"../assets/global/plugins/uniform/jquery.uniform.js",
		"../assets/global/plugins/bootstrap-switch/js/bootstrap-switch.js",
		"../assets/global/plugins/moment.js",
		"../assets/global/plugins/morris/morris.js",
		"../assets/global/plugins/morris/raphael-min.js",
		"../assets/global/plugins/jquery.sparkline.js",
		"../assets/global/plugins/counterup/jquery.waypoints.min.js",
		"../assets/global/plugins/counterup/jquery.counterup.js",
		"../assets/global/plugins/flot/jquery.flot.js",
		"../assets/global/plugins/flot/jquery.flot.resize.js",
		"../assets/global/plugins/flot/jquery.flot.categories.js",
		"../assets/global/plugins/moment.js",
		"../assets/global/plugins/bootstrap-daterangepicker/daterangepicker.js",

		"../assets/global/scripts/app.js",
		"../assets/layouts/layout/scripts/layout.js",
		"../assets/layouts/global/scripts/quick-sidebar.js",
		"../assets/layouts/layout/scripts/demo.js",

		"../assets/global/plugins/bootbox/bootbox.js",
		"../assets/global/plugins/jquery-idle-timeout/jquery.idletimeout.js",
		"../assets/global/plugins/jquery-idle-timeout/jquery.idletimer.js",
		"../assets/global/plugins/bootstrap-toastr/toastr.js",
		"../assets/pages/controller/idletimeout.js",
		"../assets/global/plugins/echarts/js/ThemeStyle.js",
		//"../assets/global/plugins/echarts/js/echarts.min.js",
		"../assets/global/plugins/require.min.js"
	]
};
module.exports = index;